
B2_BUCKET=roberts-kopia-backups
B2_BUCKET_ID=1f5c2f2945248b1faf070b18
B2_ENDPOINT=s3.us-west-004.backblazeb2.com
B2_REGION=us-west-004

B2_RETENTION_MODE=COMPLIANCE
B2_RETENTION_PERIOD=30d

KOPIA_VERSION=0.23.1

SOURCES=(
  /home
  /etc
)

VERIFY_PERCENT=5

MAX_SNAPSHOT_AGE_HOURS=26

CACHE_DIR=/var/cache/kopia
